
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASC ASTERISK AVG BAR BY CHART COMMA CUSTOM_METRIC DELETE DESC ENDS EQUALS FROM GRAPH GREATER_THAN GROUP IDENTIFIER INSERT LESS_THAN LIKE LIMIT LINE LPAREN NUMBER ORDER PIE PLOT RPAREN SELECT SEMICOLON STRING WHERE WITHquery : select_query\n             | insert_query\n             | delete_queryselect_query : SELECT select_list FROM IDENTIFIER where_clause group_by_clause plot_clause order_clause limit_clause SEMICOLONinsert_query : INSERT insert_items SEMICOLONinsert_items : insert_item COMMA insert_items\n                    | insert_iteminsert_item : IDENTIFIER EQUALS valuedelete_query : DELETE where_clause SEMICOLONvalue : NUMBER\n             | STRINGselect_list : ASTERISK\n                   | expression COMMA select_list\n                   | expressionexpression : IDENTIFIER\n                  | function_call\n                  | avg_function\n                  | custom_metricfunction_call : IDENTIFIER LPAREN arg_list RPARENavg_function : AVG LPAREN IDENTIFIER RPARENcustom_metric : CUSTOM_METRIC LPAREN IDENTIFIER COMMA arg_list RPARENarg_list : IDENTIFIER COMMA arg_list\n                | IDENTIFIERwhere_clause : WHERE condition\n                    | emptycondition : IDENTIFIER GREATER_THAN NUMBER\n                 | IDENTIFIER LESS_THAN NUMBER\n                 | IDENTIFIER EQUALS STRING\n                 | IDENTIFIER LIKE STRING\n                 | IDENTIFIER EQUALS NUMBER\n                 | IDENTIFIER ENDS WITH STRINGgroup_by_clause : GROUP BY IDENTIFIER\n                       | emptyorder_clause : ORDER BY IDENTIFIER order_direction\n                    | emptyorder_direction : ASC\n                       | DESClimit_clause : LIMIT NUMBER\n                    | emptyplot_clause : PLOT BAR GRAPH\n                   | PLOT LINE GRAPH\n                   | PLOT PIE CHART\n                   | emptyempty :'
    
_lr_action_items = {'SELECT':([0,],[5,]),'INSERT':([0,],[6,]),'DELETE':([0,],[7,]),'$end':([1,2,3,4,28,31,85,],[0,-1,-2,-3,-5,-9,-4,]),'ASTERISK':([5,25,],[10,10,]),'IDENTIFIER':([5,6,21,23,24,25,26,27,29,50,53,69,81,],[9,19,33,34,35,9,38,39,19,35,35,77,87,]),'AVG':([5,25,],[15,15,]),'CUSTOM_METRIC':([5,25,],[16,16,]),'WHERE':([7,34,],[21,21,]),'SEMICOLON':([7,17,18,20,22,32,34,40,41,42,43,49,54,55,56,57,58,60,62,65,66,68,71,73,77,78,80,82,83,84,86,88,89,90,],[-44,28,-7,31,-25,-24,-44,-6,-8,-10,-11,-44,-26,-27,-28,-30,-29,-44,-33,-31,-44,-43,-44,-35,-32,85,-39,-40,-41,-42,-38,-34,-36,-37,]),'FROM':([8,9,10,11,12,13,14,37,51,52,70,],[23,-15,-12,-14,-16,-17,-18,-13,-19,-20,-21,]),'COMMA':([9,11,12,13,14,18,35,39,41,42,43,51,52,70,],[-15,25,-16,-17,-18,29,50,53,-8,-10,-11,-19,-20,-21,]),'LPAREN':([9,15,16,],[24,26,27,]),'EQUALS':([19,33,],[30,46,]),'GROUP':([22,32,34,49,54,55,56,57,58,65,],[-25,-24,-44,61,-26,-27,-28,-30,-29,-31,]),'PLOT':([22,32,34,49,54,55,56,57,58,60,62,65,77,],[-25,-24,-44,-44,-26,-27,-28,-30,-29,67,-33,-31,-32,]),'ORDER':([22,32,34,49,54,55,56,57,58,60,62,65,66,68,77,82,83,84,],[-25,-24,-44,-44,-26,-27,-28,-30,-29,-44,-33,-31,72,-43,-32,-40,-41,-42,]),'LIMIT':([22,32,34,49,54,55,56,57,58,60,62,65,66,68,71,73,77,82,83,84,88,89,90,],[-25,-24,-44,-44,-26,-27,-28,-30,-29,-44,-33,-31,-44,-43,79,-35,-32,-40,-41,-42,-34,-36,-37,]),'NUMBER':([30,44,45,46,79,],[42,54,55,57,86,]),'STRING':([30,46,47,59,],[43,56,58,65,]),'GREATER_THAN':([33,],[44,]),'LESS_THAN':([33,],[45,]),'LIKE':([33,],[47,]),'ENDS':([33,],[48,]),'RPAREN':([35,36,38,63,64,],[-23,51,52,-22,70,]),'WITH':([48,],[59,]),'BY':([61,72,],[69,81,]),'BAR':([67,],[74,]),'LINE':([67,],[75,]),'PIE':([67,],[76,]),'GRAPH':([74,75,],[82,83,]),'CHART':([76,],[84,]),'ASC':([87,],[89,]),'DESC':([87,],[90,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_query':([0,],[2,]),'insert_query':([0,],[3,]),'delete_query':([0,],[4,]),'select_list':([5,25,],[8,37,]),'expression':([5,25,],[11,11,]),'function_call':([5,25,],[12,12,]),'avg_function':([5,25,],[13,13,]),'custom_metric':([5,25,],[14,14,]),'insert_items':([6,29,],[17,40,]),'insert_item':([6,29,],[18,18,]),'where_clause':([7,34,],[20,49,]),'empty':([7,34,49,60,66,71,],[22,22,62,68,73,80,]),'condition':([21,],[32,]),'arg_list':([24,50,53,],[36,63,64,]),'value':([30,],[41,]),'group_by_clause':([49,],[60,]),'plot_clause':([60,],[66,]),'order_clause':([66,],[71,]),'limit_clause':([71,],[78,]),'order_direction':([87,],[88,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select_query','query',1,'p_query','edsql_compiler.py',90),
  ('query -> insert_query','query',1,'p_query','edsql_compiler.py',91),
  ('query -> delete_query','query',1,'p_query','edsql_compiler.py',92),
  ('select_query -> SELECT select_list FROM IDENTIFIER where_clause group_by_clause plot_clause order_clause limit_clause SEMICOLON','select_query',10,'p_select_query','edsql_compiler.py',96),
  ('insert_query -> INSERT insert_items SEMICOLON','insert_query',3,'p_insert_query','edsql_compiler.py',100),
  ('insert_items -> insert_item COMMA insert_items','insert_items',3,'p_insert_items','edsql_compiler.py',104),
  ('insert_items -> insert_item','insert_items',1,'p_insert_items','edsql_compiler.py',105),
  ('insert_item -> IDENTIFIER EQUALS value','insert_item',3,'p_insert_item','edsql_compiler.py',113),
  ('delete_query -> DELETE where_clause SEMICOLON','delete_query',3,'p_delete_query','edsql_compiler.py',117),
  ('value -> NUMBER','value',1,'p_value','edsql_compiler.py',121),
  ('value -> STRING','value',1,'p_value','edsql_compiler.py',122),
  ('select_list -> ASTERISK','select_list',1,'p_select_list','edsql_compiler.py',126),
  ('select_list -> expression COMMA select_list','select_list',3,'p_select_list','edsql_compiler.py',127),
  ('select_list -> expression','select_list',1,'p_select_list','edsql_compiler.py',128),
  ('expression -> IDENTIFIER','expression',1,'p_expression','edsql_compiler.py',137),
  ('expression -> function_call','expression',1,'p_expression','edsql_compiler.py',138),
  ('expression -> avg_function','expression',1,'p_expression','edsql_compiler.py',139),
  ('expression -> custom_metric','expression',1,'p_expression','edsql_compiler.py',140),
  ('function_call -> IDENTIFIER LPAREN arg_list RPAREN','function_call',4,'p_function_call','edsql_compiler.py',144),
  ('avg_function -> AVG LPAREN IDENTIFIER RPAREN','avg_function',4,'p_avg_function','edsql_compiler.py',148),
  ('custom_metric -> CUSTOM_METRIC LPAREN IDENTIFIER COMMA arg_list RPAREN','custom_metric',6,'p_custom_metric','edsql_compiler.py',152),
  ('arg_list -> IDENTIFIER COMMA arg_list','arg_list',3,'p_arg_list','edsql_compiler.py',157),
  ('arg_list -> IDENTIFIER','arg_list',1,'p_arg_list','edsql_compiler.py',158),
  ('where_clause -> WHERE condition','where_clause',2,'p_where_clause','edsql_compiler.py',165),
  ('where_clause -> empty','where_clause',1,'p_where_clause','edsql_compiler.py',166),
  ('condition -> IDENTIFIER GREATER_THAN NUMBER','condition',3,'p_condition','edsql_compiler.py',170),
  ('condition -> IDENTIFIER LESS_THAN NUMBER','condition',3,'p_condition','edsql_compiler.py',171),
  ('condition -> IDENTIFIER EQUALS STRING','condition',3,'p_condition','edsql_compiler.py',172),
  ('condition -> IDENTIFIER LIKE STRING','condition',3,'p_condition','edsql_compiler.py',173),
  ('condition -> IDENTIFIER EQUALS NUMBER','condition',3,'p_condition','edsql_compiler.py',174),
  ('condition -> IDENTIFIER ENDS WITH STRING','condition',4,'p_condition','edsql_compiler.py',175),
  ('group_by_clause -> GROUP BY IDENTIFIER','group_by_clause',3,'p_group_by_clause','edsql_compiler.py',183),
  ('group_by_clause -> empty','group_by_clause',1,'p_group_by_clause','edsql_compiler.py',184),
  ('order_clause -> ORDER BY IDENTIFIER order_direction','order_clause',4,'p_order_clause','edsql_compiler.py',188),
  ('order_clause -> empty','order_clause',1,'p_order_clause','edsql_compiler.py',189),
  ('order_direction -> ASC','order_direction',1,'p_order_direction','edsql_compiler.py',196),
  ('order_direction -> DESC','order_direction',1,'p_order_direction','edsql_compiler.py',197),
  ('limit_clause -> LIMIT NUMBER','limit_clause',2,'p_limit_clause','edsql_compiler.py',201),
  ('limit_clause -> empty','limit_clause',1,'p_limit_clause','edsql_compiler.py',202),
  ('plot_clause -> PLOT BAR GRAPH','plot_clause',3,'p_plot_clause','edsql_compiler.py',209),
  ('plot_clause -> PLOT LINE GRAPH','plot_clause',3,'p_plot_clause','edsql_compiler.py',210),
  ('plot_clause -> PLOT PIE CHART','plot_clause',3,'p_plot_clause','edsql_compiler.py',211),
  ('plot_clause -> empty','plot_clause',1,'p_plot_clause','edsql_compiler.py',212),
  ('empty -> <empty>','empty',0,'p_empty','edsql_compiler.py',216),
]
